### ISSUE TITLE
http parser no longer available

### ISSUE THREAD

**Issue by shahnazari** [amirmnoohi/VPN-using-cisco-ocserv#2]
Hi
It looks like the http parser mirrored on "http://mirrors.aliyun.com/epel/7/x86_64/h/http-parser-2.0-5.20121128gitcd01361.el7.x86_64.rpm" is no longer reachable. Do u happen to have it somewhere?!

**Comment by amirmnoohi** [comment]
I just updated the RPM. also you can replace it with below link:
https://cbs.centos.org/kojifiles/packages/http-parser/2.0/5.20121128gitcd01361.el7/x86_64/http-parser-2.0-5.20121128gitcd01361.el7.x86_64.rpm
